var jobTitles = [
  "Chief Cooperation Officer",
  "Social Meteorologist",
  "Associate Color Theorist",
  "Experience Data Scientist",
  "Middle End Ninja",
  "Chief Disruption Officer",
  "Manager of Management Services",
  "Ninja Chef II",
  "Janitor++",
  "Strategic Communication Marketer",
  "Strategic Strategist",
  "Junior Pinball Maintenence Engineer",
  "Foosball Referee",
  "Hashtag Strategist",
  "SEO Guy",
  "Junior Disruptivator",
  "Senior Disruptivator",
  "Brand Gatekeeper",
  "App Deployer",
  "Local Social Mobilizer",
  "Affirmative Person",
  "Job Title Innovator",
  "Manager of Firings",
  "Engineer of Things",
  "Caffiene Specialist",
  "Javascript Framework Researcher",
  "Data Driven SEO Wizard",
  "Code Templar",
  "Development Excutive of Development",
  "Efficiency Expert",
  "Asynchronous Development Manager",
  "Taco Truck Wranger",
  "Exposed Pipe Painter",
  "Engineer In Charge Of Converting Desks Into Standing Desks",
  "Open Office Planner",
  "Apple Sycophant I",
  "Apple Sycophant II",
  "Apple Sycophant III",
  "Manager: Apple Sycophants",
  "Meeting Efficiency Strategist",
  "Accountability Debater",
  "The Uber For Human Resources",
  "Full Stack Pancake Engineer",
  "Revenue Conjurer",
  "Marketing Fungineer",
  "Ping Pong Coach",
  "Gluten Coordinator",
  "Nerdist In Residence",
  "Associate TechCruncher",
  "Burning Man Coordinator",
  "Family Evictor",
  "Displacement Bus Driver",
  "Egg Cryogenicist",
  "Metatag Resource Manager",
  "Periscope Street Team Captain",
  "Guru",
  "TED Talk Curator",
  "Hype Man"
];